development:
  adapter: postgresql
  encoding: unicode
  database: robot_factory_api_development
  host: localhost
  pool: 5
  username: robot
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: robot_factory_api_test
  host: localhost
  pool: 5
  username: robot
  password: password1